"""Shared helpers for the Pulumi exporters.

The Pulumi exporters emit two dialects from the same ArchSpec:

- TypeScript (``@pulumi/aws``, ``@pulumi/gcp``, ``@pulumi/azure-native``)
- Python    (``pulumi_aws``, ``pulumi_gcp``, ``pulumi_azure_native``)

Every user-controlled string field (``c.id``, ``c.label``, ``spec.region``,
``spec.metadata.gcp_project``...) is interpolated via :func:`_ts_string` or
:func:`_py_string` so that hostile values cannot break out of their string
literal and inject arbitrary Pulumi code. These mirror ``_hcl_quote`` in the
Terraform exporter.

The same safe-by-default posture as the v1.3 Terraform exporter applies:
S3 public access blocked, RDS encrypted with backups, EC2 IMDSv2, DynamoDB
SSE+PITR, etc.
"""

from __future__ import annotations

import re

# TypeScript identifier safety: must start with a letter/underscore/dollar and
# may contain letters, digits, underscores, dollars. We additionally lowercase
# and replace dashes with underscores so that user-supplied component IDs
# (which already pass ``[a-zA-Z_][a-zA-Z0-9_-]*``) become valid var names.
_TS_PY_VAR = re.compile(r"[^a-zA-Z0-9_]")


def _ts_string(value: object) -> str:
    """Safely-quoted TypeScript string literal for ``value``.

    Escapes backslashes, double quotes, backticks, and newlines so that
    user-controlled fields cannot escape the string literal.
    """
    s = "" if value is None else str(value)
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`").replace("\r", "\\r").replace("\n", "\\n")
    return f'"{escaped}"'


def _py_string(value: object) -> str:
    """Safely-quoted Python string literal for ``value``.

    ``repr()`` produces a Python literal with all required escaping, but for
    consistency we always emit double-quoted strings.
    """
    s = "" if value is None else str(value)
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n")
    return f'"{escaped}"'


def _var_name(component_id: str) -> str:
    """Translate a component id into a safe TypeScript / Python identifier.

    Component ids match ``[a-zA-Z_][a-zA-Z0-9_-]*``; we just convert dashes to
    underscores. We also fall back to a prefixed name if the id begins with a
    digit (which ``_ID_PATTERN`` already disallows, but the cost of being
    defensive is one ``re.match`` call).
    """
    name = _TS_PY_VAR.sub("_", component_id)
    if not name or not re.match(r"^[a-zA-Z_]", name):
        name = f"r_{name}"
    return name


def _dns_name(component_id: str) -> str:
    """DNS-safe label (lowercase, dash-separated) for resource ``name`` props."""
    return component_id.replace("_", "-").lower()


def _safe_comment(value: str | None) -> str:
    """Strip newlines so an injected ``c.label`` cannot break out of // or #."""
    if not value:
        return ""
    return value.replace("\n", " ").replace("\r", " ")


def header_ts(spec_name: str) -> list[str]:
    """Top-of-file comment for a generated index.ts."""
    return [
        "// Generated by Cloudwright (https://github.com/xmpuspus/cloudwright)",
        f"// Architecture: {_safe_comment(spec_name)}",
        "",
    ]


def header_py(spec_name: str) -> list[str]:
    """Top-of-file comment for a generated __main__.py."""
    return [
        "# Generated by Cloudwright (https://github.com/xmpuspus/cloudwright)",
        f"# Architecture: {_safe_comment(spec_name)}",
        "",
    ]


# ---------------------------------------------------------------------------
# Project file templates (Pulumi.yaml, package.json, requirements.txt).
# ---------------------------------------------------------------------------


def pulumi_yaml_ts(spec_name: str) -> str:
    """Pulumi.yaml for a TypeScript project."""
    safe_name = _safe_comment(spec_name) or "cloudwright-stack"
    project_name = _dns_name(safe_name) or "cloudwright-stack"
    description = safe_name
    return f"name: {project_name}\nruntime: nodejs\ndescription: {description}\n"


def pulumi_yaml_python(spec_name: str) -> str:
    """Pulumi.yaml for a Python project."""
    safe_name = _safe_comment(spec_name) or "cloudwright-stack"
    project_name = _dns_name(safe_name) or "cloudwright-stack"
    description = safe_name
    return f"name: {project_name}\nruntime: python\ndescription: {description}\n"


def package_json(spec_name: str, providers: set[str]) -> str:
    """package.json declaring the @pulumi/* SDK deps for the given providers."""
    safe_name = _dns_name(_safe_comment(spec_name) or "cloudwright-stack")
    deps = {
        "@pulumi/pulumi": "^3.130.0",
    }
    if "aws" in providers:
        deps["@pulumi/aws"] = "^6.56.0"
    if "gcp" in providers:
        deps["@pulumi/gcp"] = "^8.10.0"
    if "azure" in providers:
        deps["@pulumi/azure-native"] = "^2.70.0"

    dep_lines = ",\n".join(f'    "{k}": "{v}"' for k, v in sorted(deps.items()))
    return (
        "{\n"
        f'  "name": "{safe_name}",\n'
        '  "main": "index.ts",\n'
        '  "devDependencies": {\n'
        '    "@types/node": "^20"\n'
        "  },\n"
        '  "dependencies": {\n'
        f"{dep_lines}\n"
        "  }\n"
        "}\n"
    )


def requirements_txt(providers: set[str]) -> str:
    """requirements.txt for a Python Pulumi project."""
    deps = ["pulumi>=3.130.0,<4.0.0"]
    if "aws" in providers:
        deps.append("pulumi-aws>=6.56.0,<7.0.0")
    if "gcp" in providers:
        deps.append("pulumi-gcp>=8.10.0,<9.0.0")
    if "azure" in providers:
        deps.append("pulumi-azure-native>=2.70.0,<3.0.0")
    return "\n".join(deps) + "\n"


def tsconfig_json() -> str:
    """Minimal tsconfig.json for a Pulumi TypeScript project."""
    return (
        "{\n"
        '  "compilerOptions": {\n'
        '    "strict": true,\n'
        '    "outDir": "bin",\n'
        '    "target": "es2020",\n'
        '    "module": "commonjs",\n'
        '    "moduleResolution": "node",\n'
        '    "sourceMap": true,\n'
        '    "experimentalDecorators": true,\n'
        '    "pretty": true,\n'
        '    "noFallthroughCasesInSwitch": true,\n'
        '    "noImplicitReturns": true,\n'
        '    "forceConsistentCasingInFileNames": true\n'
        "  },\n"
        '  "files": ["index.ts"]\n'
        "}\n"
    )
