"""Azure service definitions."""

AZURE_SERVICES = {
    "virtual_machines": {
        "name": "Azure Virtual Machines",
        "category": "compute",
        "description": "Windows and Linux virtual machines",
        "pricing_model": "per_hour",
        "default_config": {"instance_type": "Standard_D2s_v5", "storage_gb": 30},
    },
    "azure_functions": {
        "name": "Azure Functions",
        "category": "serverless",
        "description": "Event-driven serverless compute",
        "pricing_model": "per_request",
        "default_config": {"memory_mb": 512, "avg_duration_ms": 200, "monthly_requests": 1_000_000},
    },
    "container_apps": {
        "name": "Azure Container Apps",
        "category": "containers",
        "description": "Fully managed serverless container service",
        "pricing_model": "per_vcpu_second",
        "default_config": {"vcpus": 0.5, "memory_gb": 1.0, "monthly_requests": 1_000_000},
    },
    "aks": {
        "name": "Azure Kubernetes Service",
        "category": "containers",
        "description": "Managed Kubernetes container orchestration",
        "pricing_model": "per_hour",
        "default_config": {"node_instance_type": "Standard_D2s_v5", "node_count": 3},
    },
    "app_service": {
        "name": "Azure App Service",
        "category": "compute",
        "description": "Fully managed platform for web apps and APIs",
        "pricing_model": "per_hour",
        "default_config": {"plan": "P1v3", "instances": 1},
    },
    "azure_sql": {
        "name": "Azure SQL Database",
        "category": "database",
        "description": "Fully managed SQL database engine",
        "pricing_model": "per_dtu_hour",
        "default_config": {"tier": "General Purpose", "vcores": 4, "storage_gb": 100},
    },
    "cosmos_db": {
        "name": "Azure Cosmos DB",
        "category": "database",
        "description": "Globally distributed, multi-model database",
        "pricing_model": "per_ru_hour",
        "default_config": {"request_units": 400, "storage_gb": 10},
    },
    "azure_cache": {
        "name": "Azure Cache for Redis",
        "category": "cache",
        "description": "Fully managed in-memory Redis cache",
        "pricing_model": "per_hour",
        "default_config": {"sku": "C1", "size_gb": 1.0},
    },
    "blob_storage": {
        "name": "Azure Blob Storage",
        "category": "storage",
        "description": "Massively scalable object storage for any type of data",
        "pricing_model": "per_gb",
        "default_config": {"storage_gb": 100, "access_tier": "hot"},
    },
    "service_bus": {
        "name": "Azure Service Bus",
        "category": "messaging",
        "description": "Enterprise message broker with queues and pub/sub topics",
        "pricing_model": "per_operation",
        "default_config": {"monthly_operations": 1_000_000, "tier": "standard"},
    },
    "event_hubs": {
        "name": "Azure Event Hubs",
        "category": "streaming",
        "description": "Real-time data ingestion service",
        "pricing_model": "per_throughput_unit",
        "default_config": {"throughput_units": 1, "retention_days": 1},
    },
    "azure_cdn": {
        "name": "Azure CDN",
        "category": "networking",
        "description": "Content delivery network for fast, secure delivery",
        "pricing_model": "per_gb",
        "default_config": {"estimated_gb": 500},
    },
    "app_gateway": {
        "name": "Azure Application Gateway",
        "category": "networking",
        "description": "Layer 7 web application load balancer with WAF",
        "pricing_model": "fixed_plus_cu",
        "default_config": {"sku": "WAF_v2", "capacity_units": 1},
    },
    "azure_lb": {
        "name": "Azure Load Balancer",
        "category": "networking",
        "description": "Layer 4 TCP/UDP network load balancer",
        "pricing_model": "fixed_plus_rule",
        "default_config": {"rules": 1},
    },
    "azure_dns": {
        "name": "Azure DNS",
        "category": "networking",
        "description": "Host your DNS domain in Azure",
        "pricing_model": "per_zone",
        "default_config": {"hosted_zones": 1, "monthly_queries": 1_000_000},
    },
    "azure_waf": {
        "name": "Azure Web Application Firewall",
        "category": "security",
        "description": "Web application firewall providing centralized protection",
        "pricing_model": "fixed_plus_request",
        "default_config": {"policies": 1, "monthly_requests": 10_000_000},
    },
    "synapse": {
        "name": "Azure Synapse Analytics",
        "category": "analytics",
        "description": "Limitless analytics service unifying data integration and warehousing",
        "pricing_model": "per_dwu_hour",
        "default_config": {"dwu": 100, "storage_gb": 100},
    },
    "azure_ml": {
        "name": "Azure Machine Learning",
        "category": "ml",
        "description": "End-to-end machine learning lifecycle management",
        "pricing_model": "per_hour",
        "default_config": {"instance_type": "Standard_DS3_v2", "training_hours": 10},
    },
    "azure_ad": {
        "name": "Microsoft Entra ID (Azure AD)",
        "category": "security",
        "description": "Identity and access management service",
        "pricing_model": "per_mau",
        "default_config": {"monthly_active_users": 10_000, "tier": "P1"},
    },
    "logic_apps": {
        "name": "Azure Logic Apps",
        "category": "orchestration",
        "description": "Automate workflows and integrate apps and services",
        "pricing_model": "per_action",
        "default_config": {"monthly_actions": 1_000_000},
    },
    "api_management": {
        "name": "Azure API Management",
        "category": "networking",
        "description": "Publish, secure, and analyze APIs",
        "pricing_model": "per_hour",
        "default_config": {"tier": "developer", "monthly_calls": 1_000_000},
    },
}
