"""Terraform HCL exporter — dispatches to per-provider modules."""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

from cloudwright.exporter.terraform import aws, azure, databricks, gcp
from cloudwright.exporter.terraform.common import _REQUIRED_PROVIDERS

if TYPE_CHECKING:
    from cloudwright.spec import ArchSpec, Component


def _render_resource(c: "Component", spec: "ArchSpec") -> str:
    provider = c.provider.lower()
    if provider == "aws":
        return aws.render_resource(c, spec)
    if provider == "gcp":
        return gcp.render_resource(c, spec)
    if provider == "azure":
        return azure.render_resource(c, spec)
    if provider == "databricks":
        return databricks.render_resource(c, spec)
    return f"# Unsupported provider: {provider} (component: {c.id})"


def _providers_in_spec(spec: "ArchSpec") -> set[str]:
    providers = {spec.provider.lower()}
    for c in spec.components:
        providers.add(c.provider.lower())
    return providers & _REQUIRED_PROVIDERS.keys()


def _terraform_label(value: str) -> str:
    label = re.sub(r"[^a-zA-Z0-9_]+", "_", value).strip("_").lower()
    if not label:
        return "module"
    if not re.match(r"^[a-zA-Z_]", label):
        return f"module_{label}"
    return label


def _module_blocks(spec: "ArchSpec") -> tuple[list[str], set[str]]:
    instances = (spec.metadata or {}).get("modules", {}).get("instances", {})
    if not isinstance(instances, dict):
        return [], set()

    component_ids = {component.id for component in spec.components}
    rendered: list[str] = []
    module_component_ids: set[str] = set()

    for instance_id, instance in sorted(instances.items(), key=lambda item: item[0]):
        if not isinstance(instance, dict):
            continue
        terraform = instance.get("terraform") or {}
        if not isinstance(terraform, dict) or not terraform.get("source"):
            continue
        ids = instance.get("component_ids") or []
        if not isinstance(ids, list):
            continue
        existing_ids = [component_id for component_id in ids if component_id in component_ids]
        expected_count = instance.get("expected_component_count")
        if (
            instance.get("partial")
            or not instance.get("approved", False)
            or (isinstance(expected_count, int) and len(existing_ids) != expected_count)
        ):
            continue

        label = _terraform_label(str(instance_id))
        lines = [
            f'module "{label}" {{',
            f'  source = "{terraform["source"]}"',
        ]
        if terraform.get("version"):
            lines.append(f'  version = "{terraform["version"]}"')
        lines.append("}")
        rendered.append("\n".join(lines))
        module_component_ids.update(existing_ids)

    return rendered, module_component_ids


def render(spec: "ArchSpec") -> str:
    providers = _providers_in_spec(spec)
    parts: list[str] = []

    parts.append("# Generated by Cloudwright (https://github.com/xmpuspus/cloudwright)")
    parts.append(f"# Architecture: {spec.name}")
    parts.append("")

    req_providers_lines = ["terraform {", "  required_providers {"]
    for p in sorted(providers):
        rp = _REQUIRED_PROVIDERS[p]
        req_providers_lines.append(f"    {p} = {{")
        req_providers_lines.append(f'      source  = "{rp["source"]}"')
        req_providers_lines.append(f'      version = "{rp["version"]}"')
        req_providers_lines.append("    }")
    req_providers_lines += ["  }", "}"]
    parts.append("\n".join(req_providers_lines))
    parts.append("")

    for p in sorted(providers):
        if p == "aws":
            parts.append(f'provider "aws" {{\n  region = "{spec.region}"\n}}')
        elif p == "gcp":
            project = spec.metadata.get("gcp_project", "my-gcp-project")
            region = spec.metadata.get("gcp_region", spec.region)
            parts.append(f'provider "google" {{\n  project = "{project}"\n  region  = "{region}"\n}}')
        elif p == "azure":
            parts.append('provider "azurerm" {\n  features {}\n}')
        elif p == "databricks":
            parts.append('provider "databricks" {\n  host  = var.databricks_host\n  token = var.databricks_token\n}')
        parts.append("")

    if "aws" in providers:
        parts.append('data "aws_vpc" "default" {')
        parts.append("  default = true")
        parts.append("}")
        parts.append("")
        parts.append('data "aws_subnets" "default" {')
        parts.append("  filter {")
        parts.append('    name   = "vpc-id"')
        parts.append("    values = [data.aws_vpc.default.id]")
        parts.append("  }")
        parts.append("}")
        parts.append("")
        parts.append('data "aws_ssm_parameter" "amazon_linux" {')
        parts.append('  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"')
        parts.append("}")
        parts.append("")
        parts.append('data "aws_availability_zones" "available" {')
        parts.append('  state = "available"')
        parts.append("}")
        parts.append("")
        parts.append('data "aws_caller_identity" "current" {}')
        parts.append("")

    if "azure" in providers:
        parts.append('resource "azurerm_resource_group" "main" {')
        parts.append('  name     = "rg-cloudwright"')
        parts.append('  location = "East US"')
        parts.append("}")
        parts.append("")
        parts.append('resource "azurerm_virtual_network" "main" {')
        parts.append('  name                = "vnet-cloudwright"')
        parts.append('  address_space       = ["10.0.0.0/16"]')
        parts.append("  location            = azurerm_resource_group.main.location")
        parts.append("  resource_group_name = azurerm_resource_group.main.name")
        parts.append("}")
        parts.append("")
        parts.append('resource "azurerm_subnet" "main" {')
        parts.append('  name                 = "subnet-cloudwright"')
        parts.append("  resource_group_name  = azurerm_resource_group.main.name")
        parts.append("  virtual_network_name = azurerm_virtual_network.main.name")
        parts.append('  address_prefixes     = ["10.0.1.0/24"]')
        parts.append("}")
        parts.append("")

    parts.append('variable "environment" {')
    parts.append('  default = "production"')
    parts.append("}")
    parts.append("")
    parts.append('variable "db_password" {')
    parts.append('  description = "Database password"')
    parts.append("  sensitive   = true")
    parts.append("}")
    parts.append("")
    parts.append('variable "db_username" {')
    parts.append('  description = "Database administrator username"')
    parts.append('  default     = "cloudwright_admin"')
    parts.append("}")
    parts.append("")
    parts.append('variable "account_id" {')
    parts.append('  description = "AWS account ID"')
    parts.append('  default     = ""')
    parts.append("}")
    parts.append("")
    parts.append('variable "lambda_role_arn" {')
    parts.append('  description = "IAM role ARN for Lambda functions"')
    parts.append("}")
    parts.append("")
    parts.append('variable "eks_role_arn" {')
    parts.append('  description = "IAM role ARN for EKS cluster"')
    parts.append("}")
    parts.append("")
    parts.append('variable "cloudfront_origin_domain" {')
    parts.append('  description = "Domain name for CloudFront origin"')
    parts.append('  default     = "origin.example.com"')
    parts.append("}")
    parts.append("")
    parts.append('variable "trail_bucket" {')
    parts.append('  description = "S3 bucket for CloudTrail logs"')
    parts.append('  default     = ""')
    parts.append("}")
    parts.append("")
    parts.append('variable "codepipeline_role_arn" {')
    parts.append('  description = "IAM role ARN for CodePipeline"')
    parts.append('  default     = ""')
    parts.append("}")
    parts.append("")
    parts.append('variable "artifact_bucket" {')
    parts.append('  description = "S3 bucket for pipeline artifacts"')
    parts.append('  default     = ""')
    parts.append("}")
    parts.append("")
    parts.append('variable "codestar_connection_arn" {')
    parts.append('  description = "CodeStar connection ARN for source"')
    parts.append('  default     = ""')
    parts.append("}")
    parts.append("")
    parts.append('variable "task_definition_arn" {')
    parts.append('  description = "ECS task definition ARN"')
    parts.append('  default     = ""')
    parts.append("}")
    parts.append("")

    if "databricks" in providers:
        parts.append('variable "databricks_host" {}')
        parts.append("")
        parts.append('variable "databricks_token" {')
        parts.append("  sensitive = true")
        parts.append("}")
        parts.append("")

    module_blocks, module_component_ids = _module_blocks(spec)
    if module_blocks:
        parts.append("# Modules")
        parts.extend(module_blocks)
        parts.append("")

    parts.append("# Resources")
    for c in spec.components:
        if c.id in module_component_ids:
            continue
        parts.append(_render_resource(c, spec))
        parts.append("")

    parts.append('output "architecture_name" {')
    parts.append(f'  value = "{spec.name}"')
    parts.append("}")

    return "\n".join(parts)
