#!/usr/bin/env python3
"""Format Cloudwright check results into a GitHub PR comment."""

import json
import sys
from pathlib import Path


def format_comment(results_path: str) -> str:
    raw = Path(results_path).read_text()
    sections = ["## Cloudwright Architecture Review\n"]

    current_section = None
    current_content = []

    for line in raw.strip().split("\n"):
        if line.startswith("## "):
            if current_section:
                formatted = _format_section(current_section, "\n".join(current_content))
                if formatted:
                    sections.append(formatted)
            current_section = line[3:].strip()
            current_content = []
        else:
            current_content.append(line)

    if current_section:
        formatted = _format_section(current_section, "\n".join(current_content))
        if formatted:
            sections.append(formatted)

    sections.append(
        "\n---\n*Generated by [Cloudwright](https://github.com/cloudwright/cloudwright) architecture intelligence*"
    )
    return "\n".join(sections)


def _format_section(title: str, content: str) -> str:
    content = content.strip()
    if not content:
        return ""

    # Strip markdown code fences if present (old action format)
    stripped = content
    if stripped.startswith("```json"):
        stripped = stripped[7:]
    if stripped.startswith("```"):
        stripped = stripped[3:]
    if stripped.endswith("```"):
        stripped = stripped[:-3]
    stripped = stripped.strip()

    try:
        data = json.loads(stripped)
        return _format_json_section(title, data)
    except (json.JSONDecodeError, ValueError):
        pass

    return f"### {title}\n\n{content}\n"


def _format_json_section(title: str, data) -> str:
    dispatch = {
        "Validation": _format_validation,
        "Cost Estimate": _format_cost,
        "Score": _format_score,
        "Lint": _format_lint,
        "Diff": _format_diff,
        "Policy": _format_policy,
        "Analyze": _format_analyze,
    }
    fn = dispatch.get(title)
    if fn:
        return fn(data)
    return f"### {title}\n\n```json\n{json.dumps(data, indent=2)}\n```\n"


def _format_validation(data) -> str:
    lines = ["### Compliance Validation\n"]

    results = []
    if isinstance(data, list):
        results = data
    elif isinstance(data, dict):
        results = data.get("results", [data] if "framework" in data else [])

    for result in results:
        framework = result.get("framework", "Unknown")
        passed = result.get("passed", False)
        score = result.get("score", 0)
        icon = "[PASS]" if passed else "[FAIL]"
        lines.append(f"**{icon} {framework}** — Score: {score:.0%}\n")

        checks = result.get("checks", [])
        failures = [c for c in checks if not c.get("passed", True)]
        if failures:
            lines.append("| Check | Severity | Detail |")
            lines.append("|-------|----------|--------|")
            for c in failures[:10]:
                lines.append(
                    f"| {c.get('name', '')} | {c.get('severity', '').upper()} | {c.get('detail', '')} |"
                )
            if len(failures) > 10:
                lines.append(f"| ... | | +{len(failures) - 10} more |")
            lines.append("")

    return "\n".join(lines)


def _format_cost(data) -> str:
    lines = ["### Cost Estimate\n"]

    estimate = data.get("estimate", data) if isinstance(data, dict) else data
    total = estimate.get("monthly_total", 0)
    currency = estimate.get("currency", "USD")
    tier = estimate.get("pricing_tier", "on_demand")
    lines.append(
        f"**Monthly Total: ${total:,.2f} {currency}** ({tier.replace('_', ' ').title()})\n"
    )

    breakdown = estimate.get("breakdown", [])
    if breakdown:
        lines.append("| Component | Service | Monthly | Notes |")
        lines.append("|-----------|---------|--------:|-------|")
        for item in breakdown:
            comp = item.get("component_id", "")
            svc = item.get("service", "")
            monthly = item.get("monthly", 0)
            notes = item.get("notes", "")
            source = item.get("price_source", "catalog")
            marker = f" [{source}]" if source != "catalog" else ""
            lines.append(f"| {comp} | {svc} | ${monthly:,.2f}{marker} | {notes} |")
        lines.append("")

    transfer = estimate.get("data_transfer_monthly", 0)
    if transfer > 0:
        lines.append(f"Data transfer: ${transfer:,.2f}/mo\n")

    return "\n".join(lines)


def _format_score(data) -> str:
    lines = ["### Architecture Score\n"]
    grade = data.get("grade", "?")
    total = data.get("total_score", 0)
    lines.append(f"**Grade: {grade}** ({total:.0f}/100)\n")

    dimensions = data.get("dimensions", {})
    if dimensions:
        lines.append("| Dimension | Score |")
        lines.append("|-----------|------:|")
        for dim, score in dimensions.items():
            lines.append(f"| {dim.replace('_', ' ').title()} | {score:.0f} |")
        lines.append("")

    recommendations = data.get("recommendations", [])
    if recommendations:
        lines.append("**Recommendations:**")
        for rec in recommendations[:5]:
            lines.append(f"- {rec}")
        if len(recommendations) > 5:
            lines.append(f"- ... and {len(recommendations) - 5} more")
        lines.append("")

    return "\n".join(lines)


def _format_lint(data) -> str:
    lines = ["### Lint\n"]

    issues = data if isinstance(data, list) else data.get("issues", data.get("warnings", []))
    if not issues:
        lines.append("[PASS] No issues found.\n")
    else:
        lines.append(f"Found {len(issues)} issue(s):\n")
        for warning in issues:
            if isinstance(warning, dict):
                check = warning.get("check", warning.get("rule", ""))
                msg = warning.get("message", "")
                sev = warning.get("severity", "warning")
                tag = "[ERROR]" if sev == "error" else "[WARN]"
                lines.append(f"- {tag} **{check}**: {msg}")
            else:
                lines.append(f"- {warning}")
        lines.append("")

    return "\n".join(lines)


def _format_diff(data) -> str:
    lines = ["### Architecture Diff\n"]

    summary = data.get("summary", "")
    if summary:
        lines.append(f"{summary}\n")

    cost_delta = data.get("cost_delta", 0)
    if cost_delta != 0:
        sign = "+" if cost_delta > 0 else ""
        lines.append(f"**Cost delta: {sign}${cost_delta:,.2f}/mo**\n")

    added = data.get("added", [])
    if added:
        ids = ", ".join(c.get("id", str(c)) if isinstance(c, dict) else str(c) for c in added)
        lines.append(f"**Added ({len(added)}):** {ids}")

    removed = data.get("removed", [])
    if removed:
        ids = ", ".join(c.get("id", str(c)) if isinstance(c, dict) else str(c) for c in removed)
        lines.append(f"**Removed ({len(removed)}):** {ids}")

    changed = data.get("changed", [])
    if changed:
        lines.append(f"**Modified ({len(changed)}):** " + ", ".join(
            c.get("id", str(c)) if isinstance(c, dict) else str(c) for c in changed
        ))

    impacts = data.get("compliance_impact", [])
    if impacts:
        lines.append("\n**Compliance Impact:**")
        for impact in impacts:
            lines.append(f"- {impact}")

    lines.append("")
    return "\n".join(lines)


def _format_policy(data) -> str:
    lines = ["### Policy Check\n"]

    passed = data.get("passed", False)
    icon = "[PASS]" if passed else "[FAIL]"
    deny = data.get("deny_count", len([v for v in data.get("violations", []) if v.get("severity") == "deny"]))
    warn = data.get("warn_count", len([v for v in data.get("violations", []) if v.get("severity") == "warn"]))
    lines.append(f"**{icon}** Denies: {deny}, Warnings: {warn}\n")

    violations = data.get("violations", [])
    if violations:
        for v in violations[:10]:
            severity = v.get("severity", "warn")
            tag = "[DENY]" if severity == "deny" else "[WARN]" if severity == "warn" else "[INFO]"
            rule = v.get("rule", "")
            msg = v.get("message", "")
            lines.append(f"- {tag} **{rule}**: {msg}")
        if len(violations) > 10:
            lines.append(f"- ... and {len(violations) - 10} more")
        lines.append("")

    return "\n".join(lines)


def _format_analyze(data) -> str:
    lines = ["### Blast Radius Analysis\n"]

    critical_path = data.get("critical_path", [])
    if critical_path:
        lines.append(f"**Critical path:** {' -> '.join(critical_path)}\n")

    components = data.get("components", {})
    spofs = [cid for cid, info in components.items() if isinstance(info, dict) and info.get("is_spof")]
    if spofs:
        lines.append(f"**Single Points of Failure:** {', '.join(spofs)}\n")

    if components:
        sorted_comps = sorted(
            (
                (cid, info.get("blast_radius", 0))
                for cid, info in components.items()
                if isinstance(info, dict)
            ),
            key=lambda x: x[1],
            reverse=True,
        )[:5]
        if sorted_comps:
            lines.append("| Component | Blast Radius |")
            lines.append("|-----------|------------:|")
            for cid, radius in sorted_comps:
                lines.append(f"| {cid} | {radius} |")
            lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <results-file>", file=sys.stderr)
        sys.exit(1)
    print(format_comment(sys.argv[1]))
