"""AWS service definitions."""

AWS_SERVICES = {
    "ec2": {
        "name": "Amazon EC2",
        "category": "compute",
        "description": "Virtual servers in the cloud",
        "pricing_model": "per_hour",
        "default_config": {"instance_type": "t3.medium", "storage_gb": 30},
    },
    "lambda": {
        "name": "AWS Lambda",
        "category": "serverless",
        "description": "Run code without provisioning servers",
        "pricing_model": "per_request",
        "default_config": {"memory_mb": 512, "avg_duration_ms": 200, "monthly_requests": 1_000_000},
    },
    "ecs": {
        "name": "Amazon ECS",
        "category": "containers",
        "description": "Highly secure, reliable, and scalable container orchestration",
        "pricing_model": "per_hour",
        "default_config": {"instance_type": "t3.medium", "task_count": 2},
    },
    "eks": {
        "name": "Amazon EKS",
        "category": "containers",
        "description": "Managed Kubernetes service",
        "pricing_model": "per_hour",
        "default_config": {"node_instance_type": "t3.medium", "node_count": 3},
    },
    "fargate": {
        "name": "AWS Fargate",
        "category": "containers",
        "description": "Serverless compute for containers",
        "pricing_model": "per_vcpu_hour",
        "default_config": {"vcpus": 0.5, "memory_gb": 1.0, "task_count": 2},
    },
    "rds": {
        "name": "Amazon RDS",
        "category": "database",
        "description": "Managed relational database service",
        "pricing_model": "per_hour",
        "default_config": {"instance_class": "db.t3.medium", "storage_gb": 100, "engine": "postgres"},
    },
    "aurora": {
        "name": "Amazon Aurora",
        "category": "database",
        "description": "MySQL and PostgreSQL-compatible cloud-native database",
        "pricing_model": "per_hour",
        "default_config": {"instance_class": "db.r5.large", "storage_gb": 100, "engine": "aurora-postgresql"},
    },
    "dynamodb": {
        "name": "Amazon DynamoDB",
        "category": "database",
        "description": "Fast and flexible NoSQL database service",
        "pricing_model": "per_request",
        "default_config": {"read_capacity_units": 5, "write_capacity_units": 5, "storage_gb": 10},
    },
    "elasticache": {
        "name": "Amazon ElastiCache",
        "category": "cache",
        "description": "In-memory caching service (Redis or Memcached)",
        "pricing_model": "per_hour",
        "default_config": {"node_type": "cache.t3.medium", "num_nodes": 1, "engine": "redis"},
    },
    "s3": {
        "name": "Amazon S3",
        "category": "storage",
        "description": "Object storage built to retrieve any amount of data",
        "pricing_model": "per_gb",
        "default_config": {"storage_gb": 100, "requests_per_month": 100_000},
    },
    "sqs": {
        "name": "Amazon SQS",
        "category": "messaging",
        "description": "Fully managed message queuing service",
        "pricing_model": "per_request",
        "default_config": {"monthly_requests": 1_000_000},
    },
    "sns": {
        "name": "Amazon SNS",
        "category": "messaging",
        "description": "Fully managed pub/sub messaging service",
        "pricing_model": "per_request",
        "default_config": {"monthly_publishes": 1_000_000},
    },
    "cloudfront": {
        "name": "Amazon CloudFront",
        "category": "networking",
        "description": "Content delivery network",
        "pricing_model": "per_gb",
        "default_config": {"estimated_gb": 500, "requests_per_month": 10_000_000},
    },
    "alb": {
        "name": "Application Load Balancer",
        "category": "networking",
        "description": "Layer 7 HTTP/HTTPS load balancer",
        "pricing_model": "fixed_plus_lcu",
        "default_config": {"lcu_per_hour": 1.0},
    },
    "nlb": {
        "name": "Network Load Balancer",
        "category": "networking",
        "description": "Layer 4 TCP/UDP load balancer",
        "pricing_model": "fixed_plus_lcu",
        "default_config": {"lcu_per_hour": 1.0},
    },
    "route53": {
        "name": "Amazon Route 53",
        "category": "networking",
        "description": "Scalable DNS and domain name registration",
        "pricing_model": "per_zone",
        "default_config": {"hosted_zones": 1, "monthly_queries": 1_000_000},
    },
    "waf": {
        "name": "AWS WAF",
        "category": "security",
        "description": "Web application firewall",
        "pricing_model": "fixed_plus_request",
        "default_config": {"rules": 5, "monthly_requests": 10_000_000},
    },
    "api_gateway": {
        "name": "Amazon API Gateway",
        "category": "networking",
        "description": "Create, publish, and secure APIs at scale",
        "pricing_model": "per_request",
        "default_config": {"monthly_requests": 1_000_000, "type": "rest"},
    },
    "kinesis": {
        "name": "Amazon Kinesis",
        "category": "streaming",
        "description": "Real-time data streaming service",
        "pricing_model": "per_shard_hour",
        "default_config": {"shards": 2, "data_gb_per_month": 10},
    },
    "redshift": {
        "name": "Amazon Redshift",
        "category": "analytics",
        "description": "Cloud data warehouse",
        "pricing_model": "per_hour",
        "default_config": {"node_type": "dc2.large", "num_nodes": 2},
    },
    "sagemaker": {
        "name": "Amazon SageMaker",
        "category": "ml",
        "description": "Build, train, and deploy machine learning models",
        "pricing_model": "per_hour",
        "default_config": {"instance_type": "ml.m5.xlarge", "training_hours": 10},
    },
    "cognito": {
        "name": "Amazon Cognito",
        "category": "security",
        "description": "User authentication and access control",
        "pricing_model": "per_mau",
        "default_config": {"monthly_active_users": 10_000},
    },
    "step_functions": {
        "name": "AWS Step Functions",
        "category": "orchestration",
        "description": "Visual workflow coordination for distributed applications",
        "pricing_model": "per_transition",
        "default_config": {"monthly_state_transitions": 1_000_000},
    },
    "eventbridge": {
        "name": "Amazon EventBridge",
        "category": "messaging",
        "description": "Serverless event bus connecting application data",
        "pricing_model": "per_event",
        "default_config": {"monthly_events": 1_000_000},
    },
}
