"""GCP service definitions."""

GCP_SERVICES = {
    "compute_engine": {
        "name": "Google Compute Engine",
        "category": "compute",
        "description": "Virtual machines running in Google's data centers",
        "pricing_model": "per_hour",
        "default_config": {"instance_type": "e2-medium", "storage_gb": 30},
    },
    "cloud_functions": {
        "name": "Google Cloud Functions",
        "category": "serverless",
        "description": "Event-driven serverless compute platform",
        "pricing_model": "per_request",
        "default_config": {"memory_mb": 512, "avg_duration_ms": 200, "monthly_requests": 1_000_000},
    },
    "cloud_run": {
        "name": "Google Cloud Run",
        "category": "containers",
        "description": "Fully managed containerized application platform",
        "pricing_model": "per_vcpu_second",
        "default_config": {"vcpus": 1.0, "memory_gb": 2.0, "monthly_requests": 1_000_000},
    },
    "gke": {
        "name": "Google Kubernetes Engine",
        "category": "containers",
        "description": "Managed Kubernetes service",
        "pricing_model": "per_hour",
        "default_config": {"node_instance_type": "e2-standard-2", "node_count": 3},
    },
    "app_engine": {
        "name": "Google App Engine",
        "category": "compute",
        "description": "Fully managed serverless application platform",
        "pricing_model": "per_hour",
        "default_config": {"instance_class": "F2", "idle_instances": 1},
    },
    "cloud_sql": {
        "name": "Google Cloud SQL",
        "category": "database",
        "description": "Fully managed relational database service",
        "pricing_model": "per_hour",
        "default_config": {"instance_type": "db-n1-standard-2", "storage_gb": 100, "engine": "postgres"},
    },
    "firestore": {
        "name": "Google Cloud Firestore",
        "category": "database",
        "description": "Serverless NoSQL document database",
        "pricing_model": "per_request",
        "default_config": {"reads_per_month": 1_000_000, "writes_per_month": 500_000, "storage_gb": 10},
    },
    "spanner": {
        "name": "Google Cloud Spanner",
        "category": "database",
        "description": "Horizontally scalable, globally distributed relational database",
        "pricing_model": "per_node_hour",
        "default_config": {"num_nodes": 1, "storage_gb": 100},
    },
    "memorystore": {
        "name": "Google Cloud Memorystore",
        "category": "cache",
        "description": "Fully managed in-memory data store (Redis or Memcached)",
        "pricing_model": "per_gb_hour",
        "default_config": {"memory_gb": 4.0, "engine": "redis"},
    },
    "cloud_storage": {
        "name": "Google Cloud Storage",
        "category": "storage",
        "description": "Object storage for companies of all sizes",
        "pricing_model": "per_gb",
        "default_config": {"storage_gb": 100, "storage_class": "standard"},
    },
    "pub_sub": {
        "name": "Google Cloud Pub/Sub",
        "category": "messaging",
        "description": "Asynchronous and scalable messaging service",
        "pricing_model": "per_gb",
        "default_config": {"monthly_data_gb": 10},
    },
    "cloud_cdn": {
        "name": "Google Cloud CDN",
        "category": "networking",
        "description": "Content delivery network integrated with Google's infrastructure",
        "pricing_model": "per_gb",
        "default_config": {"estimated_gb": 500},
    },
    "cloud_load_balancing": {
        "name": "Google Cloud Load Balancing",
        "category": "networking",
        "description": "High-performance, scalable load balancing",
        "pricing_model": "fixed_plus_rule",
        "default_config": {"forwarding_rules": 1},
    },
    "cloud_dns": {
        "name": "Google Cloud DNS",
        "category": "networking",
        "description": "Scalable, reliable, and managed DNS service",
        "pricing_model": "per_zone",
        "default_config": {"hosted_zones": 1, "monthly_queries": 1_000_000},
    },
    "cloud_armor": {
        "name": "Google Cloud Armor",
        "category": "security",
        "description": "DDoS protection and Web Application Firewall",
        "pricing_model": "fixed_plus_request",
        "default_config": {"policies": 1, "monthly_requests": 10_000_000},
    },
    "bigquery": {
        "name": "Google BigQuery",
        "category": "analytics",
        "description": "Serverless, highly scalable data warehouse",
        "pricing_model": "per_tb_query",
        "default_config": {"storage_gb": 100, "monthly_query_tb": 1.0},
    },
    "dataflow": {
        "name": "Google Cloud Dataflow",
        "category": "streaming",
        "description": "Unified stream and batch data processing",
        "pricing_model": "per_vcpu_hour",
        "default_config": {"vcpus": 4, "memory_gb": 16, "hours_per_month": 100},
    },
    "vertex_ai": {
        "name": "Google Vertex AI",
        "category": "ml",
        "description": "Unified ML platform for building and deploying ML models",
        "pricing_model": "per_hour",
        "default_config": {"machine_type": "n1-standard-4", "training_hours": 10},
    },
    "firebase_auth": {
        "name": "Firebase Authentication",
        "category": "security",
        "description": "Simple and secure user authentication",
        "pricing_model": "per_mau",
        "default_config": {"monthly_active_users": 10_000},
    },
    "api_gateway": {
        "name": "Google Cloud API Gateway",
        "category": "networking",
        "description": "Develop, deploy, and secure APIs",
        "pricing_model": "per_request",
        "default_config": {"monthly_requests": 1_000_000},
    },
    "workflows": {
        "name": "Google Cloud Workflows",
        "category": "orchestration",
        "description": "Orchestrate and automate Google Cloud and HTTP-based services",
        "pricing_model": "per_step",
        "default_config": {"monthly_steps": 1_000_000},
    },
}
